version: '3.8'

services:
  redis-master:
    image: redis
    container_name: redis-master
    volumes:
      - ./docker-volume/redis-master/:/data
    ports:
      - 6379:6379

  redis-slave1:
    image: redis
    container_name: redis-slave1
    volumes:
      - ./docker-volume/redis-slave1/:/data
    ports:
      - 6380:6379
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    image: redis
    container_name: redis-slave2
    volumes:
      - ./docker-volume/redis-slave2/:/data
    ports:
      - 6381:6379
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
      - redis-slave1
